spring.application.name=ProjetoAtivoOperante
spring.datasource.url=jdbc:postgresql://localhost:5433/ativo_operante
spring.datasource.username=postgres
spring.datasource.password=postgres123
springdoc.swagger-ui.path=/ativop-doc.html
